name: First workflow custom
on:
  workflow_call:
     secrets:
      MY_SECRET:
        required: false
 # push:
  #  branches:
   #   - main

jobs:
  job-checkout-and-ls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v2
        with:
          path: mainrepo
          
          
      - name: Checkout workflows repo
        uses: actions/checkout@v2
        with:
          repository: josepebel/fluffy-workflows
          ref: main
          path: workflowsrepo
          
      - name: ls and cat main repo
        shell: bash
      
        run: |
          ls
          echo "cat main repo readme"
          cat ./mainrepo/README.md
          echo "Main repo ls"
          ls ./workflowsrepo
          echo "Workflow repo ls"
          ls ${{ github.workspace}}/workflowsrepo
          
        
      - name: echo secret
        shell: bash
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        
        run: |
          chmod +x ./workflowsrepo/scripts/myscript.sh
          sh ./workflowsrepo/scripts/myscript.sh
          

      - name: Check workspace
        run: ls ${{ github.workspace}}
      - uses: actions/setup-java@v3
        with:
            distribution: 'temurin'
            java-version: '11'
            cache: 'maven'
      - name: Java version
        run: java -version
      - name: Check workspace after java installation
        run: ls ${{ github.workspace}}
      #- name: Build with Maven
      #  run: mvn -B package --file pom.xml
          
      
