name: First workflow custom
on:
  workflow_call:

 # push:
  #  branches:
   #   - main

jobs:
  job-checkout-and-ls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: mainrepo

      - name: ls and cat
        shell: bash
        run: |
          ls
          cat ./mainrepo/README.md
          
          
      - name: Checkout karate repo
        uses: actions/checkout@v2
        with:
          repository: josepeno/fluffy-workflows
          ref: main
          path: workflowsrepo
          
          
      - name: echo secret
        shell: bash
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: |
          chmod +x ./workflowsrepo/scripts/firstscript.sh
          sh ./workflowsrepo/scripts/firstscript.sh
          
      
