name: First workflow custom
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  name-of-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Hello world
        shell: bash
        run: |
          ls
      
