name: First workflow custom
on:
  workflow_call:
  push:
    branches:
      - main

jobs:
  job-checkout-and-ls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Hello world
        shell: bash
        run: |
          ls
          cat ./README.md
      
