name: First workflow custom
on:
  workflow_call:
     secrets:
      MY_SECRET:
        required: false
 # push:
  #  branches:
   #   - main

jobs:
  job-checkout-and-ls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v2
        with:
          path: mainrepo
          
          
      - name: Checkout workflows repo
        uses: actions/checkout@v2
        with:
          repository: josepebel/fluffy-workflows
          ref: main
          path: workflowsrepo
          
      - name: ls and cat main repo
        shell: bash
        env:
          MY_SECRET: $ {{secrets.MY_SECRET}}
        run: |
          ls
          echo "Main repo ls"
          cat ./mainrepo/README.md
          echo "Workflow repo ls"
          ls ./workflowsrepo
          
        
          
      - name: echo secret
        shell: bash
        run: |
          chmod +x ./workflowsrepo/scripts/myscript.sh
          sh ./workflowsrepo/scripts/myscript.sh
          
      
