name: Docker Postgres Workflow
on:
  workflow_call:
   
 

jobs:
 postgres-container:
  
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_HOST:  localhost
          POSTGRES_DB: postgres        
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    # psql -h postgres -U postgres -c 'CREATE DATABASE ...'
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v2
        with:
          path: mainrepo
      - name: Checkout workflows repo
        uses: actions/checkout@v2
        with:
          repository: josepebel/fluffy-workflows
          ref: main
          path: workflowsrepo
      - name: ls and cat main repo
        run: |
            ls
            
      - name: Check schemas
        run: |
            psql --version
            psql postgresql://postgres:postgres@localhost:5432/postgres?sslmode=prefer -c '\dn'
            
      - name: Execute script
        run: |
            chmod +x ./workflowsrepo/scripts/postgresScript.sh
            sh ./workflowsrepo/scripts/postgresScript.sh
            
      - name: Check tables
        run: |
            psql postgresql://postgres:postgres@localhost:5432/postgres?sslmode=prefer -c '\dt'
            
      - name: Insert data
        run: |
            psql postgresql://postgres:postgres@localhost:5432/postgres?sslmode=prefer -c '\i ./workflowsrepo/scripts/company.sql'
            
      - name: Check data
        run: |
            psql postgresql://postgres:postgres@localhost:5432/postgres?sslmode=prefer -c 'SELECT * FROM public.company'
            
      - name: Create new schema
        run: |
             psql postgresql://postgres:postgres@localhost:5432/postgres?sslmode=prefer -c 'CREATE SCHEMA new_schema AUTHORIZATION postgres;'
             
      - name: Check schemas again
        run: |
            psql --version
            psql postgresql://postgres:postgres@localhost:5432/postgres?sslmode=prefer -c '\dn'
            
      - name: Dump public schema
        run: |
            mkdir backups
            pg_dump --help
            pg_dump -d postgres -n public > ./backups/public.dmp
            
      - name: ls and cat main repo
        run: |
            ls
            echo "......."
            ls ./backups
     
