name: Docker Workflow
on:
  workflow_call:
   
 

jobs:
  first-container:
    runs-on: ubuntu-latest
    container: node:16.15.1
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v2
        with:
          path: mainrepo
      - name: check node version
        run: |
            node --version
            npm --version
  second-container:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_HOST:  localhost
          POSTGRES_DB: postgres        
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    # psql -h postgres -U postgres -c 'CREATE DATABASE ...'
    steps:
      - name: Check content
        run: |
            psql --version
            
            psql -h postgres -U postgres -c '\dn'


