name: Docker Workflow
on:
  workflow_call:
   
 

jobs:
  first-container:
    runs-on: ubuntu-latest
    container: node:16.15.1
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v2
        with:
          path: mainrepo
      - name: check node version
        run: |
            node --version
            npm --version
  second-container:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check content
        run: |
            psql --version

