name: Docker Workflow
on:
  workflow_call:
   
 

jobs:
  checkout-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v2
        with:
          path: mainrepo
      - name: Checkout workflows repo
        uses: actions/checkout@v2
        with:
          repository: josepebel/fluffy-workflows
          ref: main
          path: workflowsrepo
          
  first-container:
    runs-on: ubuntu-latest
    container: node:16.15.1
    steps:
      - name: check node version
        run: |
            node --version
            npm --version
  second-container:
    needs: checkout-repos
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_HOST:  localhost
          POSTGRES_DB: postgres        
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    # psql -h postgres -U postgres -c 'CREATE DATABASE ...'
    steps:
      - name: ls and cat main repo
        run: |
            ls
      - name: Check schemas
        run: |
            psql --version
            psql postgresql://postgres:postgres@localhost:5432/postgres?sslmode=prefer -c '\dn'
            
      - name: Execute script
        run: |
            chmod +x ./workflowsrepo/scripts/postgresScript.sh
            sh ./workflowsrepo/scripts/postgresScript.sh
            
            


